# HTTP Protocol
:toc:

NogDB RESTful HTTP protocol allows to talk with a NogDB Server instance using the HTTP protocol and JSON.
// NogDB supports also a highly optimized Binary protocol for superior performances.

## HTTP Method

This protocol uses only `POST` method of the HTTP protocol.

When using `POST` the following are important when preparing the contents of the post message:

- Always have the content type set to `application/json`.
- Where data or data structure is involved the content is in JSON format.

## Syntax

The REST API is flexible, with the following rules:

- Data returned is in JSON format.
- Support only http connections.
- The API itself is case sensitive.

The REST URL syntax used is the POST method:

Syntax: `+http://<server>:<port>/<category>/<operation>+`

HTTP Response can be:

- 200 OK
- 400 Bad Request
- 500 Internal Server Error
- or else.

When response "200 OK", results are always in JSON format. Example:

[source, JSON]
{
    "type": "s",
    "data": [
        {
            "descriptor": {
                "rid": [6, 7]
            },
            "record": {
                "prop1": "hello"
            }
        },
        {
            "descriptor": {
                "rid": [6, 10]
            },
            "record": {
                "prop1": "world"
            }
        }
    ]
}

## HTTP commands

### Category `Class`

#### Operation `create`

URL: `+http://<server>:<port>/Class/create+`

Body:
 
[source, subs="normal"]
{
    "className": <string>,
    "type": <<<ClassType>>>
}

Response: `<<<ClassDescriptor>>>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#create[nogdb::Class::create]

#### Operation `createExtend`

URL: `+http://<server>:<port>/Class/createExtend+`

Body:
 
[source, subs="normal"]
{
    "className": <string>,
    "superClass": <string>
}

Response: `<<<ClassDescriptor>>>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#create-extend[nogdb::Class::createExtend]

#### Operation `drop`

URL: `+http://<server>:<port>/Class/drop+`

Body:
 
[source, subs="normal"]
{
    "className": <string>
}

Response: `{}`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#drop[nogdb::Class::drop]

#### Operation `alter`

URL: `+http://<server>:<port>/Class/alter+`

Body:
 
[source, subs="normal"]
{
    "oldClassName": <string>,
    "newClassName": <string>
}

Response: `{}`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#alter[nogdb::Class::alter]

### Category `Property`

#### Operation `add`

URL: `+http://<server>:<port>/Property/add+`

Body:

[source, subs="normal"]
{
    "className": <string>,
    "propertyName": <string>,
    "type": <<<PropertyType>>>,
}

Response: `<<<PropertyDescriptor>>>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#add[nogdb::Property::add]

#### Operation `alter`

URL: `+http://<server>:<port>/Property/alter+`

Body:

[source, subs="normal"]
{
    "className": <string>,
    "oldPropertyName": <string>,
    "newPropertyName": <string>
}

Response: `{}`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#alter-1[nogdb::Property::alter]

#### Operation `remove`

URL: `+http://<server>:<port>/Property/remove+`

Body:

[source, subs="normal"]
{
    "className": <string>,
    "propertyName": <string>
}

Response: `{}`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#remove[nogdb::Property::remove]

#### Operation `createIndex`

URL: `+http://<server>:<port>/Property/createIndex+`

Body:

[source, subs="normal"]
{
    "className": <string>,
    "propertyName": <string>,
    "isUnique": <bool>
}

Response: `{}`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#create-index[nogdb::Property:createIndex]

#### Operation `dropIndex`

URL: `+http://<server>:<port>/Property/dropIndex+`

Body:

[source, subs="normal"]
{
    "className": <string>,
    "propertyName": <string>
}

Response: `{}`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#drop-index[nogdb::Property::dropIndex]

### Category `Vertex`

#### Operation `create`

URL: `+http://<server>:<port>/Vertex/create+`

Body:

[source, subs="normal"]
{
    "className": <string>,
    "record": <<<Record>>>
}

Response: `<<<RecordDescriptor>>>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#create-1[nogdb::Vertex::create]

#### Operation `update`

URL: `+http://<server>:<port>/Vertex/update+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>,
    "record": <<<Record>>>
}

Response: `{}`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#update[nogdb::Vertex::update]

#### Operation `destroy`

URL: `+http://<server>:<port>/Vertex/destroy+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>
}

or

[source, subs="normal"]
{
    "className": <string>
}

Response: 

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#destroy[nogdb::Vertex::destroy]

#### Operation `get`

URL: `+http://<server>:<port>/Vertex/get+`

Body:

[source, subs="normal"]
{
    "className": <string>
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-1[nogdb::Vertex::get]

#### Operation `getInEdge`

URL: `+http://<server>:<port>/Vertex/getInEdge+`

Body:

[source, subs="normal"]
{
    "recodeDescriptor": <<<RecordDescriptor>>>,
    "classFilter": <string[]> (OPTIONAL)
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-in-edge[nogdb::Vertex::getInEdge]

#### Operation `getOutEdge`

URL: `+http://<server>:<port>/Vertex/getOutEdge+`

Body:

[source, subs="normal"]
{
    "recodeDescriptor": <<<RecordDescriptor>>>,
    "classFilter": <string[]> (OPTIONAL)
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-out-edge[nogdb::Vertex::getOutEdge]

#### Operation `getAllEdge`

URL: `+http://<server>:<port>/Vertex/getAllEdge+`

Body:

[source, subs="normal"]
{
    "recodeDescriptor": <<<RecordDescriptor>>>,
    "classFilter": <string[]> (OPTIONAL)
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-all-edge[nogdb::Vertex::getAllEdge]

### Category `Edge`

#### Operation `create`

URL: `+http://<server>:<port>/Edge/create+`

Body:

[source, subs="normal"]
{
    "className": <string>,
    "srcVertexRecordDescriptor": <<<RecordDescriptor>>>,
    "dstVertexRecordDescriptor": <<<RecordDescriptor>>>,
    "record": <<<Record>>>
}

Response: `<<<RecordDescriptor>>>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#create-2[nogdb::Edge::create]

#### Operation `update`

URL: `+http://<server>:<port>/Edge/update+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>,
    "record": <<<Record>>>
}

Response: `{}`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#update-1[nogdb::Edge::update]

#### Operation `updateSrc`

URL: `+http://<server>:<port>/Edge/updateSrc+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>,
    "newSrcVertexRecordDescriptor": <<<RecordDescriptor>>>
}

Response: `{}` 

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#update-source[nogdb::Edge::updateSrc]

#### Operation `updateDst`

URL: `+http://<server>:<port>/Edge/updateDst+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>,
    "newDstVertexRecordDescriptor": <<<RecordDescriptor>>>
}

Response: `{}`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#update-destination[nogdb::Edge::updateDst]

#### Operation `destroy`

URL: `+http://<server>:<port>/Edge/destroy+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>
}

[source, subs="normal"]
{
     "className": <string>
}

Response: `{}`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#destroy-1[nogdb::Edge::destroy]

#### Operation `get`

URL: `+http://<server>:<port>/Edge/get+`

Body:

[source, subs="normal"]
{
    "className": <string>
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-2[nogdb::Edge::get]

#### Operation `getSrc`

URL: `+http://<server>:<port>/Edge/getSrc+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>
}

Response: `<<<Result>>>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-source[nogdb::Edge::getSrc]

#### Operation `getDst`

URL: `+http://<server>:<port>/Edge/getDst+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>
}

Response: `<<<Result>>>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-destination[nogdb::Edge::getDst]

#### Operation `getSrcDst`

URL: `+http://<server>:<port>/Edge/getSrcDst+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-source--destination[nogdb::Edge::getSrcDst]

### Category `Db`

#### Operation `getRecord`

URL: `+http://<server>:<port>/Db/getRecord+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>
}

Response: `<<<Record>>>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-record[nogdb::Db::getRecord]

#### Operation `getSchema`

URL: `+http://<server>:<port>/Db/getSchema+`

Body:

[source, subs="normal"]
{
    "className": <string>
}

or

[source, subs="normal"]
{
    "classId": <number>
}

Response: `<<<ClassDescriptor>>>`

or

Body: `{}`

Response: `<<<ClassDescriptor>>[]>

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-schema[nogdb::Db::getSchema]

#### Operation `getDbInfo`

URL: `+http://<server>:<port>/Db/getDbInfo+`

Body: `{}`

Response: `<<<DBInfo>>>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#get-db-info[nogdb::Db::getDbInfo]

### Category `Traverse`

#### Operation `inEdgeBfs`

URL: `+http://<server>:<port>/Traverse/inEdgeBfs+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>,
    "minDepth": <number>,
    "maxDepth": <number>,
    "classFilter": <string[]> (OPTIONAL)
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#bfs-traverse-in-edge[nogdb::Traverse::inEdgeBfs]

#### Operation `outEdgeBfs`

URL: `+http://<server>:<port>/Traverse/outEdgeBfs+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>,
    "minDepth": <number>,
    "maxDepth": <number>,
    "classFilter": <string[]> (OPTIONAL)
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#bfs-traverse-out-edge[nogdb::Traverse::outEdgeBfs]

#### Operation `allEdgeBfs`

URL: `+http://<server>:<port>/Traverse/allEdgeBfs+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>,
    "minDepth": <number>,
    "maxDepth": <number>,
    "classFilter": <string[]> (OPTIONAL)
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#bfs-traverse-all-edge[nogdb::Traverse::allEdgeBfs]

#### Operation `inEdgeDfs`

URL: `+http://<server>:<port>/Traverse/inEdgeDfs+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>,
    "minDepth": <number>,
    "maxDepth": <number>,
    "classFilter": <string[]> (OPTIONAL)
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#dfs-traverse-in-edge[nogdb::Traverse::inEdgeDfs]

#### Operation `outEdgeDfs`

URL: `+http://<server>:<port>/Traverse/outEdgeDfs+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>,
    "minDepth": <number>,
    "maxDepth": <number>,
    "classFilter": <string[]> (OPTIONAL)
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#dfs-traverse-out-edge[nogdb::Traverse::outEdgeDfs]

#### Operation `allEdgeDfs`

URL: `+http://<server>:<port>/Traverse/allEdgeDfs+`

Body:

[source, subs="normal"]
{
    "recordDescriptor": <<<RecordDescriptor>>>,
    "minDepth": <number>,
    "maxDepth": <number>,
    "classFilter": <string[]> (OPTIONAL)
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#dfs-traverse-all-edge[nogdb::Traverse::allEdgeDfs]

#### Operation `shortestPath`

URL: `+http://<server>:<port>/Traverse/shortestPath+`

Body:

[source, subs="normal"]
{
    "srcVertexRecordDescriptor": <<<RecordDescriptor>>>,
    "dstVertexRecordDescriptor": <<<RecordDescriptor>>>,
    "classFilter": <string[]> (OPTIONAL)
}

Response: `<<<Result>>[]>`

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#shortest-path[nogdb::Traverse::shortestPath]

### Category `SQL`

#### Operation `execute`

URL: `+http://<server>:<port>/SQL/execute+`

Body:

[source, subs="normal"]
{
    "sql": <string>
}

Response: `<<<SQL::Result>>>`

## Data Structure

### Error::Type

[source]
"d" (DATASTORE)
"g" (GRAPH)
"c" (CONTEXT)
"t" (TRANSACTION)
"s" (SQL)

### Error

[source, subs="normal"]
{
    "type": <<<Error::Type>>>,
    "code": <number>,
    "what": <string>
}

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#error-handling[nogdb::Error]

### DBInfo

[source]
{
    "dbPath": <string>,
    "maxDB": <number>,
    "maxDBSize": <number>,
    "maxPropertyId": <number>,
    "numProperty": <number>,
    "maxClassId": <number>,
    "numClass": <number>,
    "maxIndexId": <number>,
    "numIndex": <number>
}

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#database-information[nogdb::DBInfo]

### PropertyType

[source]
"i" (TINYINT)
"I" (UNSIGNED_TINYINT)
"s" (SMALLINT)
"S" (UNSIGNED_SMALLINT)
"d" (INTEGER)
"D" (UNSIGNED_INTEGER)
"l" (BIGINT)
"L" (UNSIGNED_BIGINT)
"t" (TEXT)
"f" (REAL)
"b" (BLOB)
"n" (UNDEFINED)

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#types-of-properties[nogdb::PropertyType]

### PropertyDescriptor

[source, subs="normal"]
{
    "id": <number>,
    "type": <<<PropertyType>>>,
    "indexInfo": <<<IndexInfo>>>
}

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#property-descriptor[nogdb::PropertyDescriptor]

### ClassType

[source]
"v" (VERTEX)
"e" (EDGE)
"n" (UNDEFINED)

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#class-types[nogdb::ClassType]

### ClassDescriptor

[source, subs="normal"]
{
    "id": <number>,
    "name": <string>,
    "type": <<<ClassType>>>,
    "properties": {
        <string>: <<<PropertyDescriptor>>>,
        . . .
    },
    "super": <string>,
    "sub": <string[]>
}

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#class-descriptor[nogdb::ClassDescriptor]

### RecordDescriptor

[source]
{
    "rid": [<ClassID>, <PosID>]
}

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#record-descriptor[nogdb::RecordDescriptor]

### Bytes

[source]
<string>|<number>

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#bytes[nogdb::Bytes]

### Record

[source, subs="normal"]
{
    <string>: <<<Bytes>>>,
    . . .
}

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#record[nogdb::Record]

### Result

[source, subs="normal"]
{
    "descriptor": <<<RecordDescriptor>>>,
    "record": <<<Record>>>
}

See also: https://github.com/nogdb/nogdb/blob/develop/doc/manual.adoc#result-result-set-and-result-set-cursor[nogdb::Result]

### SQL::Result::Type

[source]
"n" (NO_RESULT)
"e" (ERROR)
"c" (CLASS_DESCRIPTOR)
"p" (PROPERTY_DESCRIPTOR)
"r" (RECORD_DESCRIPTORS)
"s" (RESULT_SET)

### SQL::Result

[source, subs="normal"]
----
{
    "type": <<<SQL::Result::Type>>>,

    // relate on type
    "data":
        null
        | <<<Error>>>
        | <<<ClassDescriptor>>>
        | <<<PropertyDescriptor>>>
        | <<<RecordDescriptor>>[]>
        | <<<Result>>[]>
}
----
